spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: idyllo
    url: jdbc:mysql://127.0.0.1/mstore?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: select 'x'
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000

server:
  servlet:
    context-path: /mstore

#logging:
#  level:
#    cn.llman.dao.mapper: trace

mybatis:
  configuration:
    map-underscore-to-camel-case: true
